### ISSUE TITLE
Opzet maken om proxy indicator per land te kunnen berekenen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/NetworkModel_EU#1]

**Comment by cjacobscrisioni** [comment]
.. Met origin en destination punten steeds alleen binnen de grenzen van een lidstaat. De proxy wordt in de praktijk al gebruikt voor het doorrekenen van het downscalen van nationale statistieken mbt autokilometers per capita. Nu een poging om de indicator ook te gebruiken voor het kwantificeren van de tijdskosten van congestie. Mogelijk wordt de EEA gevraagd om de proxy structureel door te gaan rekenen met verschillende bevolkingsgrids. Nog onduidelijk of dat zal gaan gebeuren met Tom Tom of OSM netwerken.

**Comment by cjacobscrisioni** [comment]
All changes done and made available in congestion_dgregio branch. 

First results including speed profile delay effects are computed, seem plausible
