### ISSUE TITLE
TomTom network simplification leads to subnetworks on previously fully connected network

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/NetworkModel_EU#6]

**Comment by cjacobscrisioni** [comment]
Rond de getroffen origins zijn links met direction = 2 (forwards) en direction = 3 (backwards). Deze lijken te worden platgeslagen tot onedirection ja / nee, nog geen link inversies gevonden die nodig zijn

**Comment by cjacobscrisioni** [comment]
In /NetworkSetup/Base_Analysis/NetwerkSpec/CreateInitialWorkingNetwork/Roads is alleen OneDirection beschikbaar. Dit is de arc2segm operatie. Daaropvolgend zou waarschijnlijk het best een linkinversie kunnen gebeuren (ie als direction==3 dan first_point = nextpoint en last_point = point).

**Comment by cjacobscrisioni** [comment]
Als ik de od matrix genereer zonder bidirectional flag (dus gewoon alle richtingen goed) dan vult de matrix volledig met (overigens veel lagere) reistijden. Dus het probleem is op behoorlijk zeker gelinked aan richtingen issues.

**Comment by cjacobscrisioni** [comment]
In /NetworkSetup/Base_Analysis/NetwerkSpec/CreateMoreEfficientNetwork/OptimiseNetwork/Iter_0/JunctionFreeSection/Links_InsideJFS_IsOneDirection wordt nu onedirection alleen overgenomen als alle links binnen een JFS onedirectional zijn. An sich zou dat scherper mogen -> maar eerst testen of het omdraaien van links goed gaat.

**Comment by cjacobscrisioni** [comment]
Testaanpassing: ik draai in /NetworkSetup/Base_Analysis/NetwerkSpec/CreateInitialWorkingNetwork/Roads/Connectable de link om als de direction = 3. Door middel van tijdelijke punten p1:= Direction != 3 ? point : nextpoint; p2:= Direction != 3 ? nextpoint : point;

**Comment by jipclaassens** [comment]
Die omdraaiing gebeurt al veel eerder hier: /SourceData/Infrastructure/TomTom/FSS/Streets_Selectie/F_JNCTID_directed

Zit daar dan de fout?

**Comment by cjacobscrisioni** [comment]
> Die omdraaiing gebeurt al veel eerder hier: /SourceData/Infrastructure/TomTom/FSS/Streets_Selectie/F_JNCTID_directed
> 
> Zit daar dan de fout?

Had ik nog niet eens gezien - is niet fout maar redundant; vanaf CreateInitialWorkingNetwork maakt de methode nodes op basis van unieke geometrieën, niet meer obv de jnctids van TomTom. Omdat geometrieën in Streets_selectie niet worden omgedraaid, raakt de omdraaiing zo kwijt.

Daarop voortbordurend, het is aantrekkelijk om de inversie al te doen in SourceData/Infrastructure/TomTom/FSS/Streets_Selectie . Dat kan vrij simpel in cleaned_geometrie (neem de laatste n+1 punten ipv de eerste). Maar is er wel van afhankelijk dat aangeleverde netwerk persistent fout zijn.

Doordenkend: ik heb een aantal plekken gezien waar kruispunten worden gemaakt terwijl wegen elkaar daar alleen _kruisen_ volgens TomTom. Bijvoorbeeld bij viaducten. Beetje een dilemma - de arc2segm gebeurt om snel od punten te connecten. Maar daarmee raken we nu de TomTom topologie kwijt.

**Comment by jipclaassens** [comment]
**Bug gevonden:** 
Deze 

`/SourceData/Infrastructure/TomTom/selection/Make_Streets_selection/F_JNCTID `

verwijst naar 

`/SourceData/Infrastructure/TomTom/FSS/Streets_Selectie/F_JNCTID`
 
ipv

`/SourceData/Infrastructure/TomTom/FSS/Streets_Selectie/F_JNCTID_directed`

**Comment by jipclaassens** [comment]
Bevindingen over OD_roads:

Hier is het nog correct:
`/NetworkSetup/Base_Analysis/NetwerkSpec/CreateInitialWorkingNetwork/LinkSet_Read/IsOD_connection_road`

**Comment by jipclaassens** [comment]
Over de F1 / F2 die verkeerdom lijken te zijn bij die eenrichting wegen:

Hieronder zie je Last/First_ConnectorLink_rel van een JFS. En de gehighlightete ConnectorLink. Dat is de rechter rijbaan, dus rijrichitng van onder naar boven. Dit zou dus de last connector link moeten zijn. Maar is de eerste. Voor de weg aan de andere kant is dit wel juist.

![image](https://github.com/ObjectVision/NetworkModel_EU/assets/48675272/4f567a1e-90a7-44ff-acbe-ef9faaf08a34)

**Comment by jipclaassens** [comment]
Dit is raar:

Zie recht, geen onedirection:
![image](https://github.com/ObjectVision/NetworkModel_EU/assets/48675272/0f69143a-e987-4a12-9760-b285d5346220)

Terwijl deze dat wel heeft. En deze heeft rekenregel:
```
Links_InsideJFS_IsOneDirection     := all(LinksInsideJunctionFreeSection/IsOneDirection, LinksInsideJunctionFreeSection/JunctionFreeSection_rel)
```
![image](https://github.com/ObjectVision/NetworkModel_EU/assets/48675272/a7eea1d5-0b23-490a-b7f3-32d56740634e)

JFS_rel lijkt vaak niet gedefinieerd, dus hoe gaat die all(bool, rel) ?

![image](https://github.com/ObjectVision/NetworkModel_EU/assets/48675272/dca76804-f48c-437b-a217-291ec4a40b72)

**Comment by jipclaassens** [comment]
Fixed!
```
					attribute<NodeSet>                         Fa                             := ConnectorLink/NodeSet_rel[First_ConnectorLink_rel];
					attribute<NodeSet>                         Fb                             := ConnectorLink/NodeSet_rel[Last_ConnectorLink_rel];  
					
					attribute<NodeSet>                         F1                             :=  First_ConnectorLink_rel -> F1 == Fa ? Fa : Fb;
					attribute<NodeSet>                         F2                             :=  First_ConnectorLink_rel -> F1 == Fa ? Fb : Fa;
```

**Comment by cjacobscrisioni** [comment]
Ik snap de context nog niet maar het ziet er logisch uit. Al getest?

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/NetworkModel_EU/assets/48675272/d414ea8e-56c3-4d40-8020-90f50ab33ce5)

**Comment by jipclaassens** [comment]
Die twee vakjes linksonder:

Deze twee OD's zijn geconnect met een weg, die verbonden is met het netwerk met een enkele eenrichtingsweg, naar de OD's toe. Dit zit in de bron TomTom data...

![image](https://github.com/ObjectVision/NetworkModel_EU/assets/48675272/903e4abf-d19c-49cc-8275-b592e98ad47e)
